In [2]:
import pandas as pd

In [102]:
df_cities_static = pd.read_csv('../data/proc_data/cities_static.csv.zip', index_col=0)
df_cities_temp = pd.read_csv('../data/proc_data/cities_temp.csv.zip', parse_dates=[2], index_col=0)

In [103]:
df_cities_temp

,city_name,city_code,date,state,withdrawal,cable_tv_accesses,fixed_bandwidth_accesses,fixed_telephony_accesses,2G_mobile_accesses,3G_mobile_accesses,4G_mobile_accesses,confirmed_acc,deaths_acc,death_rate,confirmed_day,deaths_day
0,ABAÍRA,2900108,2020-04-13,BA,0.571,979,220,735.0,580.0,661.0,2354.0,1,0,0.0000,0.0,0.0
1,ABAÍRA,2900108,2020-04-14,BA,0.556,979,220,735.0,580.0,661.0,2354.0,1,0,0.0000,0.0,0.0
2,ABAÍRA,2900108,2020-04-15,BA,0.596,979,220,735.0,580.0,661.0,2354.0,1,0,0.0000,0.0,0.0
3,ABAÍRA,2900108,2020-04-16,BA,0.588,979,220,735.0,580.0,661.0,2354.0,1,0,0.0000,0.0,0.0
4,ABAÍRA,2900108,2020-04-17,BA,0.500,979,220,735.0,580.0,661.0,2354.0,1,0,0.0000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164488,VOTUPORANGA,3557105,2021-02-22,SP,0.390,3004,8405,13934.0,6518.0,9833.0,83850.0,7699,143,0.0186,6.0,0.0
164489,VOTUPORANGA,3557105,2021-02-23,SP,0.390,3004,8405,13934.0,6518.0,9833.0,83850.0,7720,144,0.0187,21.0,1.0
164490,VOTUPORANGA,3557105,2021-02-24,SP,0.380,3004,8405,13934.0,6518.0,9833.0,83850.0,7832,145,0.0185,112.0,1.0
164491,VOTUPORANGA,3557105,2021-02-25,SP,0.400,3004,8405,13934.0,6518.0,9833.0,83850.0,7859,146,0.0186,27.0,1.0
164492,VOTUPORANGA,3557105,2021-02-26,SP,0.400,3004,8405,13934.0,6518.0,9833.0,83850.0,7911,147,0.0186,52.0,1.0